### ISSUE TITLE
关于脚本使用的疑问

### ISSUE THREAD

**Issue by yingfeng-i** [Ericwyn/webdav-backup#1]
本人非程序员，只是工作与IT相关，应该算是半个网工，代码大部分都看看不懂。
不过天天接触服务器和网络，各种乱七八糟的多少懂一点，现有类似的需求，所以对关于脚本的使用有几个疑问，希望可以得到回答

1. 本地备份目录是否是在 "TargetDir": "target-local-backup-dir-full-path" 的分号中填写

2. 配置文件是否支持配置多个webdav备份对应位置（大概是{***配置1***}{***配置2***}......{***配置n***}）这样，中间是否要用逗号之类的隔开？

我也是在一台服务器部署了Seafile，用于团队文件协作共享，之前是在家中使用一台蜗牛直接跑WinSer做NAS，现NAS换成了一台万由的，他的底层的Debian系统，现在想在上面部署这个脚本实现几个特定资料库（文件夹）的同步备份

根据 README.md 中的描述，这个脚本是直接是遍历所挂载webdav的所有目录，然后备份也是备份所挂载的webdav的所有目录？
如果我只想备份某及个文件夹（即Seafile中的某几个资料库），是否可以在配置 "BaseUrl": "https://test.dav", 此处的时候连接填写到目录为止（比如 “http://xxx.xxx/seafdav/工作” 这样），应该可以吧，webdav好像是可以这样挂载吧？但是中文是不是又会有问题？

另外就是上面所问到的，配置文件是否支持配置多个webdav备份对应位置（有多个文件夹需要备份，但是不用全部备份），如何去分隔多个配置。
如果不支持大概可以多用用几个配置文件？
定时任务多写几条，每跳不同的配置文件，或者先塞进一个脚本，定时任务执行这个脚本之类的（套娃？）

./webdavBackup -c "/etc/webdavBackup-1.json" -m "backup" 
./webdavBackup -c "/etc/webdavBackup-2.json" -m "backup" 
...
./webdavBackup -c "/etc/webdavBackup.json" -m "backup"

**Comment by yingfeng-i** [comment]
感觉这个是不是可以塞进Docker里，要备份的目录挂载进去

**Comment by Ericwyn** [comment]
1. 本地备份目录是否是在 "TargetDir": "target-local-backup-dir-full-path" 的分号中填写
对，在里面填写你要下载的位置

2. 配置文件是否支持配置多个webdav备份对应位置（大概是{配置1}{配置2}......{配置n}）这样，中间是否要用逗号之类的隔开？
目前暂时不支持，只能用你提到的方式，使用多个任务来实现,  多个任务之间应该也没啥冲突吧？

./webdavBackup -c "/etc/webdavBackup-1.json" -m "backup"
./webdavBackup -c "/etc/webdavBackup-2.json" -m "backup"
...
./webdavBackup -c "/etc/webdavBackup.json" -m "backup"

3. 关于 docker，感觉做成 docker 也没太大必要，你终归是要写 json 配置之类的，机器上面写几个配置然后用 cron 定时运行好像更加方便点？ 毕竟 webdavBackup 没有额外的软件环境依赖

**Comment by Ericwyn** [comment]
BaseUrl 可以填写到目录为止~ 比如你提到的那样

**Comment by Ericwyn** [comment]
其实你的需求里面 "现NAS换成了一台万由的，他的底层的Debian系统"，我觉得首选还是在 nas 上面安装 seafile 客户端，用seafile 客户端来做同步，底层基于 debian 的话你直接用 apt 可能就可以装好 seafile 命令行工具了

**Comment by yingfeng-i** [comment]
> 其实你的需求里面 "现NAS换成了一台万由的，他的底层的Debian系统"，我觉得首选还是在 nas 上面安装 seafile 客户端，用seafile 客户端来做同步，底层基于 debian 的话你直接用 apt 可能就可以装好 seafile 命令行工具了

主要是考虑到但在在docker中比较方便管理（不包括配置），这样我所跑的各种服务都是单独的一个docker，想停和开都比较方便，需要同步到的位置挂载进去就好了。从这个角度考虑用Docker还是比较优雅的，而且万由nas提供的Docker管理工具也挺好用用的。

还是比较纠结怎么去做这个备份，我甚至考虑在Docker中去跑Seafile的cli客户端了，不过在官方的文档中好像没看到他们cli客户端能不能设置同步间隔啥的。

目前和Seafile同内网的那台备份机的实现方式不是用的官方的方法，不过在我看来也算是简单粗暴的骚操作

我直接在备份机上安装了WinSer，并在上面安装了Seafile的客户端。
然后在服务器新建一个账号，将需要同步的库只读共享给这个账号。
最后通过客户端用备份账号对这些库做同步，并设置同步时间。

并且还启用备份机的WinSer的卷影副本功能，凌晨自动给备份盘做个卷影副本（应该也是一直镜像？）
这样实现对需要备份的文件整体的备份，而且本身还附带了历史版本的功能，如果服务端崩了，备份的文件马上就是可以使用了，无需等待。

跑题了，不过跑跑着发现我好像又可以骚操作了，既然备份机是WinSer，而且文件已经是文件原来的形态了，我好像可以直接备份备份机，nas作为备份的备份（开始套娃....）

**Comment by Ericwyn** [comment]
> > 其实你的需求里面 "现NAS换成了一台万由的，他的底层的Debian系统"，我觉得首选还是在 nas 上面安装 seafile 客户端，用seafile 客户端来做同步，底层基于 debian 的话你直接用 apt 可能就可以装好 seafile 命令行工具了
> 
> 主要是考虑到但在在docker中比较方便管理（不包括配置），这样我所跑的各种服务都是单独的一个docker，想停和开都比较方便，需要同步到的位置挂载进去就好了。从这个角度考虑用Docker还是比较优雅的，而且万由nas提供的Docker管理工具也挺好用用的。
> 
> 还是比较纠结怎么去做这个备份，我甚至考虑在Docker中去跑Seafile的cli客户端了，不过在官方的文档中好像没看到他们cli客户端能不能设置同步间隔啥的。
> 
> 目前和Seafile同内网的那台备份机的实现方式不是用的官方的方法，不过在我看来也算是简单粗暴的骚操作
> 
> 我直接在备份机上安装了WinSer，并在上面安装了Seafile的客户端。 然后在服务器新建一个账号，将需要同步的库只读共享给这个账号。 最后通过客户端用备份账号对这些库做同步，并设置同步时间。
> 
> 并且还启用备份机的WinSer的卷影副本功能，凌晨自动给备份盘做个卷影副本（应该也是一直镜像？） 这样实现对需要备份的文件整体的备份，而且本身还附带了历史版本的功能，如果服务端崩了，备份的文件马上就是可以使用了，无需等待。
> 
> 跑题了，不过跑跑着发现我好像又可以骚操作了，既然备份机是WinSer，而且文件已经是文件原来的形态了，我好像可以直接备份备份机，nas作为备份的备份（开始套娃....）

套哇笑死哈哈哈哈，虽然也可以正常跑就是了
其实我觉得 docker 里面跑 seafile cli 客户端这个方案可能更好一点
